### ISSUE TITLE
Results not matching help files

### ISSUE THREAD

**Issue by Smart-Ace-Designs** [PoshMongo/PoshMongo#33]
First off, thank you for providing this module.  I truly appreciate it.

I am trying to follow along with your documentation.  When I use the Get-MongoDBDocument cmdlet, I am expecting the "_id" to be returned (as shown in your documentation).  Instead, it is returning a nested object that includes various other pairs but not the "_id" key/value pair itself.  For example:

![image](https://github.com/PoshMongo/PoshMongo/assets/132539186/6d39cb54-8c30-4b91-9542-6dec45672a72)

From looking at your documentation, I would expect it to return the actual "_id" for that document.
![image](https://github.com/PoshMongo/PoshMongo/assets/132539186/f918b028-ee5a-4c13-8a31-318374e58012)

So, I am not sure if I am doing something wrong, or perhaps there has been changes with the MongoDB API, or something else, such that the documentation is no longer accurate.  I tried using your exact example, but I could not get that to work either, without including a MongoCollection object in the command (I get an error if I don't use that):

![image](https://github.com/PoshMongo/PoshMongo/assets/132539186/4ac93d8d-28b2-4a2e-9ecd-516b69c87065)
(Note: I also tried playing around with the quotes, using single quotes vs. double quotes, etc. and I get the same results, so my screenshots don't show your exact example, but I did try it all ways)

I am using PowerShell 7.3, if that matters, and the free version of MongoDB Atlas (not a local version).

Assuming I am doing things correctly, how would one convert what is returned to find the actual "_id" value of the document?
Thanks again.

**Comment by jeffpatton1971** [comment]
Sorry, just saw this, I don't think you're doing anything wrong at all. I'm not a mongo expert by any stretch, but from what I understand the _id is a special field that can be either a GUID or UUID which contains A LOT more data, your shot above. In my example case I was passing in the _id during the creation of the document, if I remember correctly. 

So, is the ask here, to go from MongoDB UUID to System.GUID? Or are you asking for clarification?

**Comment by Smart-Ace-Designs** [comment]
No worries.  To be honest, I can't remember what I was trying to do anymore...lol.  I was trying to learn MongoDB and figured I would try my hand at seeing if I could get some value out of it with PowerShell at the time.  I will have to go back and review what I was trying to do again to figure out where I was getting hung up.

So, all good.  When I get some time, I will try it again to figure where I got stuck.

**Comment by Smart-Ace-Designs** [comment]
I did a little more work on this tonight.  I guess what I am expecting to see is something like this:
ObjectId("64d59a673c3093e5a2b86519") or just the string component of it ("64d59a673c3093e5a2b86519") which would match what I see when I use Compass or mongosh to look at the document.

But instead, I am getting an object, as shown in the screenshot, that includes the TimeStamp, MachineID, PID, etc. key/value pairs and I am not what that even represents in MongoDB.  There is nothing in what is being returned that matches the true "_id" value that I see in Compass.

So I am wondering how I get the actual ObjectId value ("_id") using your module for a document in a MongoDB collection.  Something like this (as viewed in Compass):
![image](https://github.com/PoshMongo/PoshMongo/assets/132539186/86cdbd34-e312-4200-8346-3d97731af503)

Thanks again.

**Comment by jeffpatton1971** [comment]
I think this may be an issue in the documentation to be honest, but I've also made some changes since. I'm going to close this out if you're still having issues let me know, I will run through the documentation today and make changes.

```powershell
# JeffreyPatton@FSTNQL1 | 09:14:08 | 07-19-2024 | [88.41GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [issue-33 ≡ +1 ~2 -0 !]
Get-MongoDBDocument -MongoCollection $MC -Filter '{"AccountName": "DIB"}' |ConvertFrom-Json

_id           : e68829bc-425e-4aea-a93f-a81465b4ef60
Message       : OK
LastUpdated   : 20240518T06:00:07
...

# JeffreyPatton@FSTNQL1 | 09:14:27 | 07-19-2024 | [88.41GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [issue-33 ≡ +1 ~2 -0 !]
Get-MongoDBDocument -MongoCollection $MC -Filter '{"AccountName": "DIB"}' -HideId |ConvertFrom-Json

Message       : OK
LastUpdated   : 20240518T06:00:07
...

# JeffreyPatton@FSTNQL1 | 09:16:09 | 07-19-2024 | [88.41GB] D:\CODE\Organizations\PoshMongo\PoshMongo $  [issue-33 ≡ +1 ~2 -0 !]
```
